# build an image for homework on XV6 educational operating system.
# This is built on top of the Checker code

FROM  python_base

RUN apt-get update && apt-get install -y build-essential g++ qemu qemu-kvm

WORKDIR /app
EXPOSE 8000
CMD ["gunicorn", "-b", "0.0.0.0:8000", "--workers", "10", "serverpkg.server:app"]

