# to build:
# docker build -t python_cmake_base -f Dockerfile_base .
FROM  python:3.6-stretch
MAINTAINER Noam Cohen "cnoam@technion.ac.il"
RUN apt update -y && \
 apt install -y build-essential && \
 apt install -y cmake g++ && \
 apt install -y qemu

# add /usr/bin/time since the bash version is not good for my needs
# for some obscure reason, Docker does not copy from the absolute path
# so BEFORE running it, I "cp /usr/bin/time ."
COPY  ./time /usr/bin/time
# upgrade cmake 
WORKDIR /tmp
ADD https://github.com/Kitware/CMake/releases/download/v3.14.2/cmake-3.14.2-Linux-x86_64.sh  /tmp
RUN  chmod +x cmake-3.14.2-Linux-x86_64.sh && ./cmake-3.14.2-Linux-x86_64.sh --skip-license && rm cmake-3.14.2-Linux-x86_64.sh
ENV PATH="/tmp/bin:${PATH}"

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt






