#!/bin/bash -eu

#http://jobs.eastus.cloudapp.azure.com/
mkdir -p ./logs
export CHECKER_LOG_DIR=./logs
export SPARK_CLUSTER_NAME=spark96224
export LIVY_PASS=%Qq12345678
export SPARK_PKEY_PATH=./checker_data/data/96224/spark_client
gunicorn -b 0.0.0.0:8000 \
         --workers 10 \
         --timeout 20 \
         --log-level debug \
         -c  serverpkg/gunicorn_config.py \
         serverpkg.server:app
