# setup for Spark job submitter + supporting Redis
#
# Strongly recommended: Before deploying, run
#  docker-compose config | grep WARN
version: '3'
services:
  storage:
    image: redis/redis-stack
    restart: unless-stopped

  submitter:
    image: server
    restart: unless-stopped
    ports:
      - '80:8000'
    environment:
      CHECKER_DATA_DIR : /data
      CHECKER_LOG_DIR : /logs
      SPARK_CLUSTER_NAME : $CLUSTER_NAME
      SPARK_PKEY_PATH : $SPARK_PKEY_PATH
      LIVY_PASS : $LIVY_PASS
      STORAGE_NAME : $STORAGE_NAME
      SECRET_SIG : $SECRET_SIG
    volumes:
      - $CHECKER_DATA_DIR/logs:/logs
      - $CHECKER_DATA_DIR:/data
